apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "RocketAIHub",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "olm",
              "app.kubernetes.io/name": "rocketaihub-operator"
            },
            "name": "rocketaihub"
          },
          "spec": {
            "components": {
              "gpuOperator": true
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-05-15T20:12:13Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: rocketaihub-operator.v0.0.1
  namespace: placeholder
  labels:
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/os.linux: supported
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: RocketAIHub is the Schema for the rocketaihubs API
        displayName: Rocket AIHub
        kind: RocketAIHub
        name: rocketaihubs.operator.ibm.com
        version: v1alpha1
  description: This is the operator for Rocket AI Hub which provides AI and machine learning (ML) capabilities optimized for IBM Power systems.
  displayName: Rocket AI Hub operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - persistentvolumeclaims
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - serviceaccounts
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - services
              verbs:
                - '*'
            - apiGroups:
                - admissionregistration.k8s.io
              resources:
                - mutatingwebhookconfigurations
              verbs:
                - '*'
            - apiGroups:
                - admissionregistration.k8s.io
              resources:
                - validatingwebhookconfigurations
              verbs:
                - '*'
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - autoscaling
              resources:
                - horizontalpodautoscalers
              verbs:
                - '*'
            - apiGroups:
                - batch
              resources:
                - jobs
              verbs:
                - '*'
            - apiGroups:
                - cert-manager.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - config.openshift.io
              resources:
                - ingresses
              verbs:
                - '*'
            - apiGroups:
                - integreatly.org
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - kubeflow.org
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - maistra.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - metacontroller.k8s.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - networking.istio.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - networking.k8s.io
              resources:
                - networkpolicies
              verbs:
                - '*'
            - apiGroups:
                - nfd.openshift.io
              resources:
                - nodefeaturediscoveries
              verbs:
                - '*'
            - apiGroups:
                - oauth.openshift.io
              resources:
                - oauthclients
              verbs:
                - '*'
            - apiGroups:
                - operator.ibm.com
              resources:
                - rocketaihubs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - operator.ibm.com
              resources:
                - rocketaihubs/finalizers
              verbs:
                - update
            - apiGroups:
                - operator.ibm.com
              resources:
                - rocketaihubs/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - operator.knative.dev
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - operators.coreos.com
              resources:
                - operatorgroups
              verbs:
                - '*'
            - apiGroups:
                - operators.coreos.com
              resources:
                - subscriptions
              verbs:
                - '*'
            - apiGroups:
                - project.openshift.io
              resources:
                - projects
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterrolebindings
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterroles
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
              verbs:
                - '*'
            - apiGroups:
                - redhatcop.redhat.io
              resources:
                - namespaceconfigs
              verbs:
                - '*'
            - apiGroups:
                - redhatcop.redhat.io
              resources:
                - userconfigs
              verbs:
                - '*'
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
              verbs:
                - '*'
            - apiGroups:
                - route.openshift.io
              resources:
                - routes/custom-host
              verbs:
                - '*'
            - apiGroups:
                - scheduling.k8s.io
              resources:
                - priorityclasses
              verbs:
                - '*'
            - apiGroups:
                - security.istio.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - serving.kserve.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: rocketaihub-operator-controller-manager
      deployments:
        - label:
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/name: rocketaihub-operator
            control-plane: controller-manager
          name: rocketaihub-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=0
                    image: gcr.io/kubebuilder/kube-rbac-proxy@sha256:771a9a173e033a3ad8b46f5c00a7036eaa88c8d8d1fbd89217325168998113ea
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 5m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                  - args:
                      - --health-probe-bind-address=:8081
                      - --metrics-bind-address=127.0.0.1:8080
                      - --leader-elect
                    command:
                      - /manager
                    image: quay.io/williamxiang/rocketaihub-operator@sha256:ab00ef591962921b4dcf88d17064fa1b5b9cccc4d526520d563194b772852c4a
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      requests:
                        cpu: 100m
                        memory: 128Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: rocketaihub-operator-controller-manager
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: rocketaihub-operator-controller-manager
    strategy: deployment
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - AI
    - ML
  links:
    - name: Rocketaihub Operator
      url: https://rocketaihub-operator.domain
  maturity: alpha
  provider:
    name: IBM
  relatedImages:
    - image: gcr.io/kubebuilder/kube-rbac-proxy@sha256:771a9a173e033a3ad8b46f5c00a7036eaa88c8d8d1fbd89217325168998113ea
      name: kube-rbac-proxy
    - image: quay.io/williamxiang/rocketaihub-operator@sha256:ab00ef591962921b4dcf88d17064fa1b5b9cccc4d526520d563194b772852c4a
      name: manager
  version: 0.0.1
