apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: rocketaihub-realm
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    clients:
      - redirectUris: []
        webOrigins:
          - "https://kubeflow.CLUSTER_DOMAIN_PLACEHOLDER"
        clientId: rocketaihub
        enabled: true
        secret: CLIENT_SECRET_PLACEHOLDER
        clientAuthenticatorType: client-secret
        publicClient: false
        protocol: openid-connect
        standardFlowEnabled: true
        directAccessGrantsEnabled: true
    users:
      - credentials:
          - type: password
            value: "12341234"
        enabled: true
        username: user
        email: user@example.com
    id: rocketaihub
    realm: rocketaihub
    enabled: true
    displayName: Rocket AI Hub
    rememberMe: true
    displayNameHtml: <b>Rocket AI Hub</b>
