apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Seamless Upgrades
    containerImage: quay.io/williamxiang/rocketaihub-operator@sha256:d0c954eb2a2a256fc4dd6322bd30f33efd6259d20d4b7c9b2e673e6b6006c618
    repository: https://github.com/william-xiang/rocket-ai-hub-operator.git
  name: rocketaihub-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: RocketAIHub is the Schema for the rocketaihubs API
      displayName: Rocket AIHub
      kind: RocketAIHub
      name: rocketaihubs.operator.ibm.com
      version: v1alpha1
  description: This is the operator for Rocket AI Hub which provides AI and machine
    learning (ML) capabilities optimized for IBM Power systems.
  displayName: Rocket AI Hub operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - AI
  - ML
  links:
  - name: Rocket AI Hub for IBM Power Announcement
    url: https://www.ibm.com/docs/en/announcements/rocket-ai-hub-power
  maturity: beta
  provider:
    name: IBM
  version: 0.0.0
