apiVersion: operator.ibm.com/v1alpha1
kind: RocketAIHub
metadata:
  labels:
    app.kubernetes.io/name: rocketaihub-operator
    app.kubernetes.io/managed-by: olm
  name: rocketaihub
spec:
  components:
    gpuOperator: true
  identityProvider:
    createDefaultUser: true
    existingIdentityProvider: ""