//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Component) DeepCopyInto(out *Component) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Component.
func (in *Component) DeepCopy() *Component {
	if in == nil {
		return nil
	}
	out := new(Component)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Components) DeepCopyInto(out *Components) {
	*out = *in
	out.Katib = in.Katib
	out.KServe = in.KServe
	out.KubeflowPipelines = in.KubeflowPipelines
	out.TrainingOperator = in.TrainingOperator
	out.KubeflowNotebooks = in.KubeflowNotebooks
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Components.
func (in *Components) DeepCopy() *Components {
	if in == nil {
		return nil
	}
	out := new(Components)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Katib) DeepCopyInto(out *Katib) {
	*out = *in
	out.Component = in.Component
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Katib.
func (in *Katib) DeepCopy() *Katib {
	if in == nil {
		return nil
	}
	out := new(Katib)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kserve) DeepCopyInto(out *Kserve) {
	*out = *in
	out.Component = in.Component
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kserve.
func (in *Kserve) DeepCopy() *Kserve {
	if in == nil {
		return nil
	}
	out := new(Kserve)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeflowNotebooks) DeepCopyInto(out *KubeflowNotebooks) {
	*out = *in
	out.Component = in.Component
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeflowNotebooks.
func (in *KubeflowNotebooks) DeepCopy() *KubeflowNotebooks {
	if in == nil {
		return nil
	}
	out := new(KubeflowNotebooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeflowPipelines) DeepCopyInto(out *KubeflowPipelines) {
	*out = *in
	out.Component = in.Component
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeflowPipelines.
func (in *KubeflowPipelines) DeepCopy() *KubeflowPipelines {
	if in == nil {
		return nil
	}
	out := new(KubeflowPipelines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RocketAIHub) DeepCopyInto(out *RocketAIHub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RocketAIHub.
func (in *RocketAIHub) DeepCopy() *RocketAIHub {
	if in == nil {
		return nil
	}
	out := new(RocketAIHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RocketAIHub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RocketAIHubList) DeepCopyInto(out *RocketAIHubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RocketAIHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RocketAIHubList.
func (in *RocketAIHubList) DeepCopy() *RocketAIHubList {
	if in == nil {
		return nil
	}
	out := new(RocketAIHubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RocketAIHubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RocketAIHubSpec) DeepCopyInto(out *RocketAIHubSpec) {
	*out = *in
	out.Components = in.Components
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RocketAIHubSpec.
func (in *RocketAIHubSpec) DeepCopy() *RocketAIHubSpec {
	if in == nil {
		return nil
	}
	out := new(RocketAIHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RocketAIHubStatus) DeepCopyInto(out *RocketAIHubStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RocketAIHubStatus.
func (in *RocketAIHubStatus) DeepCopy() *RocketAIHubStatus {
	if in == nil {
		return nil
	}
	out := new(RocketAIHubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperator) DeepCopyInto(out *TrainingOperator) {
	*out = *in
	out.Component = in.Component
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperator.
func (in *TrainingOperator) DeepCopy() *TrainingOperator {
	if in == nil {
		return nil
	}
	out := new(TrainingOperator)
	in.DeepCopyInto(out)
	return out
}
